### PR TITLE
If memdump enabled, but no mem analysis requested, delete mem dump if…

### PR DESCRIPTION
**Pull request by geudrik**
… configged to do so

### CODE REVIEW

**Comment by geudrik** [comment]
I was originally hesitant to PR this, but in my configuration currently, I have memory and procmemory both enabled. Via API submissions (is where I noticed the problem, I assume same result when submitted through webUI), if the equiv of "process memory dump" (web ui) isn't specified, but delete_memdump is set to True, the dump will never be removed because /processing/modules/memory is never executed

**Comment by brad-sp** [comment]
Process memory dumps are different from full memory dump.  Process memory dumps are handled in procmemory.py, while full memory dumps are handled in memory.py.  There shouldn't be any full memory dump created unless it's specifically requested.

**Comment by geudrik** [comment]
I'll double check things on my end, but full mem dumps (a full 4Gig file for each run) are being created, regardless of whether or not mem analysis is requested. They're being deleted correctly when full mem analysis is requested, but not deleted otherwise.

**Comment by brad-sp** [comment]
KillerInstinct just informed me about the memory_dump option in cuckoo.conf.  If that's enabled, then indeed full memory dumps would be created for each analysis.  They won't, however, be analyzed with volatility (that requires the full memory dump option to be enabled at analysis time).  So instead of forcing removal of the created memory dumps when the analysis option isn't enabled, I think the correct solution would be to simply set memory_dump = False in cuckoo.conf.  It doesn't prevent you from creating and analyzing memory dumps for each analysis of interest.

**Comment by geudrik** [comment]
Spent some time digging through the code - I was thinking that this might be the case. This also makes good sense. Appreciate the feedback Brad/KillerInstinct :)

**Pull request closed without merging**
