### PR TITLE
Sniff KVM vnet interface without wrapping tcpdump

### PR DESCRIPTION
**Pull request by seanthegeek**
Reschedule auxiliary modules to run after the VM starts, but before
analysis starts, so the VM interfaces are up before the sniffer module
runs

Lookup KVM interface to sniff to sniff at runtime, unless a per-machine
interface has been configured. It will use the first interface it finds if there is one.

This should eliminate the need for the KVM Tor workaround described in
the FAQ

### CODE REVIEW

**Comment by seanthegeek** [comment]
@brad-accuvant I'm having a couple of problems with the PCAPs,  and I'm not sure if its due to these changes, or because I switched from Ubuntu LTS to Debian Stable (due to newer KVM). The checksums are invalid. URL analysis ends before the page is loaded. Could you see if you get the same results?

**Comment by seanthegeek** [comment]
@brad-accuvant  I fixed it! Turns out, unless you pass `-k none` to Suricata, a single bad packet checksum will stop processing, it's all or nothing. The "invalid" packets were caused by LLMNR, which sends out a ton of UDP broadcast traffic when browsers are used. Disabling that in my VM fixed the bad traffic, but I made Suri more forgiving to avoid similar problems in the future. I updated the docs too.

This PR now ready

**Comment by KillerInstinct** [comment]
@wmetcalf is my goto for suricata stuff, though I have not historically had issues with bad checksums since correcting my adapter using ethtool per http://pevma.blogspot.com/2014/03/suricata-prepearing-10gbps-network.html (scroll about 1/3 the way down)

**Comment by seanthegeek** [comment]
Ah, I see. That guide disables checksum offloading with:

> ethtool -K eth3 rx off
> ethtool -K eth3 tx off

Because the KVM `vnet0...n` interfaces are created on-demand when the VM starts, I don't think `ethtool` settings would stick. By passing `-k none` to Suricata as I've done in this patch, I'm telling Suri to ignore bad checksums, so it has a similar effect, just at a different layer. It will still trigger alerts for bad checksums in that case though, so I added that signiture ID to the modules ignore list. I got the solution from [a Suricata support diagram](https://redmine.openinfosecfoundation.org/attachments/download/1022/no_alerts.png). Although, now that I look at that again, I notice it says to use `-k none` **OR** disable checksum offloading. So I'll add make disabling checksum checking at the Suri level an option in `processing.conf`, with a default setting of `no`, and a note to enable this if you are using KVM.    

I just checked, and VirtualBox has all the right offloading ssettings on `vboxnet0` by default, which is why I never saw bad alerts from the LLMNR traffic before.

I wish I would have known about @wmetcalf's registry keys for Cuckoo guests before I built mine. Those things are handy!

**Comment by brad-sp** [comment]
I think it should be fine without the processing.conf option.

**Comment by seanthegeek** [comment]
Yeah, I don't see how disabling checksum checks at two layers (NIC and Suri) would harm anything; the capitalized OR in the diagram made me second guess myself.

**Comment by brad-sp** [comment]
I was initially a little concerned about this sniffing change having the potential of being racy, but even the original code had a small chance of that, so I think this is fine.

**Comment by brad-sp** [comment]
I may need to revert this change.  It seems to be causing me to lose visibility of network traffic that is definitely happening in the VM.

**Pull request merged**
