### PR TITLE
Workaround for Suricata bug 1554

### PR DESCRIPTION
**Pull request by seanthegeek**
See https://redmine.openinfosecfoundation.org/issues/1554

### CODE REVIEW

**Comment by brad-sp** [comment]
BTW, why are you using your own script instead of something like oinkmaster to update rules?

**Comment by seanthegeek** [comment]
Honestly, because it was a good programming exercise :) And oinkmaster seemed like overkill when I just needed updates from one feed without management. I can replace the reference to my script with oinkmaster if you like.

**Comment by KillerInstinct** [comment]
Do you know if this breaks processing for Suricata 2.0.8? The beta version isn't in the Ubuntu PPA's yet that I'm aware of. 

I'm not fond of an update strategy which requires me to recompile. :)
EDIT: Also I'm not sure about running the beta version (PPA in your config notes) in production -- thoughts?

**Comment by seanthegeek** [comment]
It shouldn't because I wrote I wrote the batch to be forgiving of the of the bug, while still following the same basic logic. However, I encountered an issue on my system where 2.0.8 was not generating any IDs in the log lines (which breaks the script before and after my patch), so I tried the beta, and it did not have that bug. I mentioned this to the Ubuntu maintainer in an email chain, but I don't know if this has been rolled up in my original report or not.

**Comment by KillerInstinct** [comment]
I am not sure, but I don't think I see this bug in my install to begin with:

```
cuckoo@cuckoo:/opt/cuckoo/storage/analyses/1616/logs$ suricata -V
This is Suricata version 2.0.8 RELEASE

cuckoo@cuckoo:/opt/cuckoo/storage/analyses/1616/logs$ cat files-json.log
{ "id": 823, "timestamp": "09\/28\/2015-09:09:16.065306", "ipver": 4, "srcip": "184.51.126.170", "dstip": "10.0.68.12", "protocol": 6, "sp": 80, "dp": 49218, "http_uri": "\/msdownload\/update\/v3\/static\/trustedr\/en\/authrootstl.cab", "http_host": "www.download.windowsupdate.com", "http_referer": "<unknown>", "http_user_agent": "Microsoft-CryptoAPI\/6.1", "filename": "\/msdownload\/update\/v3\/static\/trustedr\/en\/authrootstl.cab", "magic": "Microsoft Cabinet archive data, 50006 bytes, 1 file", "state": "TRUNCATED", "stored": false, "size": 48484 }
{ "id": 824, "timestamp": "09\/28\/2015-09:13:28.464169", "ipver": 4, "srcip": "104.238.136.31", "dstip": "10.0.68.12", "protocol": 6, "sp": 80, "dp": 49175, "http_uri": "\/", "http_host": "icanhazip.com", "http_referer": "<unknown>", "http_user_agent": "Mozilla\/5.0 (Windows NT 6.1; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/45.0.2454.99 Safari\/537.36", "filename": "\/", "magic": "ASCII text", "state": "CLOSED", "md5": "1409871e8dcd790723ae18eef702d86c", "stored": true, "size": 15 }

cuckoo@cuckoo:/opt/cuckoo/storage/analyses/1616/logs$ ls files
file.823  file.823.meta  file.824  file.824.meta

```

EDIT: Ahh, I do see the one log has stored:false despite actually being stored. But my logs do have ID's in tact.

**Comment by seanthegeek** [comment]
Odd. The `stored:false` is legitimate on that line because the file was truncated (i.e. was not successfully stored). I now suspect that the bug might have something to do with the way a pcap of `vboxnet0` is recorded by `tcpdump`. I had to send them a pcap so they could reproduce the bug.

I'm guessing you're using KVM? I'm working on migrating now. I guess my workaround has the side-effect of capturing files that were not fully sent. Is that a feature, or a bug?

**Comment by KillerInstinct** [comment]
I'm using ESXi on this installation. So Cuckoo (Results Server) is a separate VM, and the analysis VM's just use the results server as a transparent bridge.

**Comment by KillerInstinct** [comment]
Also, I haven't applied your work around yet, hence my question if it breaks 2.0.8 :)

**Pull request merged**
