### PR TITLE
New machinery module for vSphere/ESXi

### PR DESCRIPTION
**Pull request by jgajek**
This is a vSphere/ESX machinery module for the Cuckoo sandbox and is intended as an alternative to Cuckoo's ESX machinery module.

It adds full memory dump functionality during analysis, which is currently not supported by Cuckoo's LibVirt-based ESX module.

The module depends on the vSphere API Python Bindings provided by VMware (https://github.com/vmware/pyvmomi) which can be installed via pip:

sudo pip install --upgrade pyvmomi

### CODE REVIEW

**Comment by brad-sp** [comment]
Hi Jacob,

Excellent, after reading: http://community.cuckoosandbox.org/posts/show/esx-machinery-memory-dump-support/ this is exactly what I had been waiting for (though I don't use ESXi myself).  Could you do me a favor though and please explicitly list the license or add a reference to docs/LICENSE (if it's intended to be GPLv3)?

Thanks!
-Brad

**Comment by jgajek** [comment]
Hi Brad, which license would you like it under?  I don't really care, since
I have permission in writing from my boss to contribute it upstream.

**Comment by brad-sp** [comment]
That's entirely up to you.  The rest of Cuckoo (modulo some small bits under more permissive licenses) is under GPLv3.

**Comment by jgajek** [comment]
Added reference to docs/LICENSE.

**Comment by brad-sp** [comment]
Thanks very much!  Just merged it separately since you pulled in a different fix for an issue I resolved with another commit.

Thanks again,
-Brad

**Pull request closed without merging**
