### PR TITLE
Enhanced Summary Information Useful for Analysis :)

### PR DESCRIPTION
**Pull request by MerX1030**
a couple of additions to Summary class
- Segregated data to be more descriptive and helpful.
  e.g. 
  --read_key becomes read_entries
  --delete_keys is segregated to delete_keys and delete_entries, 
  --etc.
- Added read_entries, write_entries, delete_entries, and remote_threads.
- Added details to created_services.
- Removed duplicate data and classified them to what group they really belong
  e.g.
  --items in delete_keys remain only in delete_keys and not in keys
  --items in write_files remain only in write_files and not in files

### CODE REVIEW

**Comment by brad-sp** [comment]
I'll take a close look at this tomorrow and provide some useful feedback -- from reading the description, I may not want some of these changes as there are some reasons for why things are done the way they are currently.

**Comment by brad-sp** [comment]
What I'd like to add actually is code to cuckoomon to check for the existence of a file prior to calls to CreateFile/etc so that we can add an additional argument to send back to flag whether that file was actually created or not.  Then we could have separate categories for created files and modified files.

**Comment by MerX1030** [comment]
That would also be good to have in cuckoomon. Specially when you're dealing with crypto-ransomware or file-infectors.

As for my mods, I tried to maximize the data from the cuckoomon logs (BSON) as to not force myself to look at the behavior logs when analyzing but rather look first at the summary.

One case scenario is when a sample created/modified a registry entry in .*\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies but I don't know what registry entry value and data, I just know what registry key the entry was created/modified.

I also see this as an enhancement for signature creation. It would lessen the false positives because you know what exactly the sample does. In fact I have slightly modified the community signatures to fit my mods and worked great.

**Comment by brad-sp** [comment]
Yes, something that's needed is logging of previous data when a registry key is modified.  There's quite a bit of code, particularly some in IE related to proxy settings, where it reads out the value, then writes back the same value.  It had previously thrown off one of the signatures as it thought the settings were being changed.  I've seen this also with file association keys.

**Comment by brad-sp** [comment]
I'm not liking the look of the default-collapsed information -- it needs some sort of styling instead of a plain underlined link.  I'm also not sure about default-collapsing the file details and screenshots -- these both can contain useful data at a quick glance that might be missed if one has to click on them first.  If there's a way to preserve the current look, but make that somehow collapsible (just not default-collapsed) I think that would be better.

**Comment by MerX1030** [comment]
We could always use the default view. It's just my preference on my part which data I wanted to see first. But it's okay if it's not collapsible. I was just lazy in scrolling down. ;)

**Comment by MerX1030** [comment]
I'm thinking of just creating another class in behavior.py called "ExtendedSummary" so my mods would not conflict the current "Summary" class.
I'd update you once done.
Thanks!

**Comment by MerX1030** [comment]
Finished editing behavior.py. :)
Minimal changes to Summary class and just added and ExtendedSummary class.

**Pull request closed without merging**
